### ISSUE TITLE
Request: add giscuss

### ISSUE THREAD

**Issue by banghasan** [Renovamen/vuepress-theme-gungnir#19]
add giscuss please.. https://giscus.app/

**Comment by Renovamen** [comment]
Hi! [vuepress-plugin-giscus](https://www.npmjs.com/package/vuepress-plugin-giscus) for **Vuepress 2** is avaliable on npm, it can be installed by:

```bash
yarn add vuepress-plugin-giscus@next
```

Also see [here](https://github.com/Renovamen/vuepress-theme-gungnir/tree/v2/packages/plugins/giscus) for its source code and documentation.

However, as for now, there is no plan to support Vuepress 1 due to my limit time (I'm now working on moving theme Gungnir to Vuepress 2, see [here](https://github.com/Renovamen/vuepress-theme-gungnir/tree/v2) for progress), but prs are welcome!
