### ISSUE TITLE
@renovamen/vuepress-plugin-mermaid@next didn't work

### ISSUE THREAD

**Issue by wn0x00** [Renovamen/vuepress-theme-gungnir#21]
i use typora to write markdown, can use mermaid instead mermaidjs?
```mermaidjs
xxxx
```
```mermaid
xxxx
```
i use this plugin can't work well ,

**Comment by Renovamen** [comment]
Hi, Vuepress uses [Prism](https://github.com/PrismJS/prism) as default syntax highlighter, which supports language `mermaid`. To avoid the conflict with Prism, I have to use `mermaidjs` for this plugin (~~or the code would be rendered as a mermaid code block rather that a diagram~~ Edit: at least in VuePress 2, the code would still be rendered as a diagram, but Prism's `language-mermaid` would become invalid).

I know it is incompatible with Typora, but I haven't come up with other workarounds.

**Comment by Renovamen** [comment]
Hi, v2.0.0-alpha.19 supports customizing the code block token (https://github.com/Renovamen/vuepress-theme-gungnir/commit/54b6a003f3550d082f513ddcd8bba82ca473f24d) for plugin-mermaid, see https://github.com/Renovamen/vuepress-theme-gungnir/issues/46 for details. Which means, if you still want to use token `mermaid` instead of `mermaidjs` and don't care about the conflict between this plugin and Prism, just:

```js
module.exports = {
  plugins: [
    [
      "@renovamen/vuepress-plugin-mermaid", {
        token: "mermaid"
      }
    ]
  ]
}
```
